### ISSUE TITLE
linux上No module named 'msvcrt'

### ISSUE THREAD

**Issue by Fumeng24** [WAADRI/ChaoXing_node_signin#1]
msvcrt 模块是专门为 Windows 系统设计的，因此在非 Windows 系统上无法使用。

**Comment by WAADRI** [comment]
> msvcrt 模块是专门为 Windows 系统设计的，因此在非 Windows 系统上无法使用。

是的，你这么一提醒我想起来了，现在把那块改成了按回车键退出了
