### ISSUE TITLE
不理解也不尊重，我长时间不登录就冻结？

### ISSUE THREAD

**Issue by NianBroken** [WAADRI/ChaoXing_node_signin#3]
学习通都不管我有没有登录，你一个第三方的系统反而还管我长时间不登录就冻结？

![image](https://github.com/user-attachments/assets/9b2b26ee-ba23-42fb-8726-4f060a6bcbed)

**Comment by WAADRI** [comment]
冻结是为了筛选不用的人方便以后从数据库里面删除账号信息，又不是不给你用，你要是要用的话申请解冻也不费多长时间吧，如果不用的话也不是只有我这里可以签到，你完全可以找别人的去签到吧，而且过段时间把你的账号信息从数据库里面删除了你也不用担心信息泄露。
