### ISSUE TITLE
IM消息获取

### ISSUE THREAD

**Issue by xnixianshituandui** [WAADRI/ChaoXing_node_signin#7]
IM可以获取历史消息么？怎么拉取的呀？我看web的IM只能获取最新的，历史的没法获取。我看这个里面可以获取历史的

**Comment by Misaka-1314** [comment]
历史消息没法获取，只要点进去已读了，就获取不到了

**Comment by xnixianshituandui** [comment]
> 历史消息没法获取，只要点进去已读了，就获取不到了

作者这个我看就会在IM登录之后就会自动获取IM登录前的消息，不知道是什么原理

**Comment by Misaka-1314** [comment]
> 作者这个我看就会在IM登录之后就会自动获取IM登录前的消息，不知道是什么原理

那是没有已读的消息，已读的就无了。你只要在官方App里点进去聊天了，再到作者这个系统里启动监控，就没有了

**Comment by xnixianshituandui** [comment]
> > 作者这个我看就会在IM登录之后就会自动获取IM登录前的消息，不知道是什么原理
> 
> 那是没有已读的消息，已读的就无了。你只要在官方App里点进去聊天了，再到作者这个系统里启动监控，就没有了

应该如何获取未读消息呀

**Comment by Misaka-1314** [comment]
> 应该如何获取未读消息呀

我看了作者的代码，似乎是会 通过ws下发未读消息的ID，然后需要传ID给服务器，服务器才会下发完整的消息内容。

1066行的 `first_get_taskinfo` 函数是处理未读消息的ID，环信IM的加密逻辑过于复杂，我已经放弃了。原计划是想将它移植到原生微信小程序的。

**Comment by Misaka-1314** [comment]
或许 @WAADRI 能帮助我们。🥺我是学生，请免费帮我[不是]

**Comment by WAADRI** [comment]
网页版IM确实只能获取未读消息，已读消息是获取不到的，也许可以去看看环信SDK里面有没有对应的接口？

**Comment by Misaka-1314** [comment]
> 网页版IM确实只能获取未读消息，已读消息是获取不到的，也许可以去看看环信SDK里面有没有对应的接口？

我仔细阅读环信的文档了，已读消息只有一个 需要管理员权限的接口，导出聊天记录。

**Comment by xnixianshituandui** [comment]
conference.easemob.com

> 网页版IM确实只能获取未读消息，已读消息是获取不到的，也许可以去看看环信SDK里面有没有对应的接口？

大佬，这个未读消息是有什么接口可以获取么

**Comment by Misaka-1314** [comment]
> 大佬，这个未读消息是有什么接口可以获取么

消息没有 REST API，只有 WS 接口，一堆加解密。

我本想直接使用环信SDK，然而环信网站上全是 4.x 版本的。学习通用的还是古老的 3.x 版本。

**Comment by xnixianshituandui** [comment]
> > 大佬，这个未读消息是有什么接口可以获取么
> 
> 消息没有 REST API，只有 WS 接口，一堆加解密。
> 
> 我本想直接使用环信SDK，然而环信网站上全是 4.x 版本的。学习通用的还是古老的 3.x 版本。

有老版本的文档可以看，
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/5e2bd0fe-1ba4-4313-92c9-2a7c50abcd4f">

**Comment by xnixianshituandui** [comment]
<img width="783" alt="image" src="https://github.com/user-attachments/assets/40e2e80b-147e-4602-a878-e10ee882e82c">

**Comment by xnixianshituandui** [comment]
貌似有一些线索但是思路还是不太清楚

**Comment by Misaka-1314** [comment]
> > 消息没有 REST API，只有 WS 接口，一堆加解密。
> > 我本想直接使用环信SDK，然而环信网站上全是 4.x 版本的。学习通用的还是古老的 3.x 版本。
> 
> 有老版本的文档可以看， <img alt="image" width="1116" src="https://private-user-images.githubusercontent.com/175671363/386829556-5e2bd0fe-1ba4-4313-92c9-2a7c50abcd4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NDM2NTAsIm5iZiI6MTczMTc0MzM1MCwicGF0aCI6Ii8xNzU2NzEzNjMvMzg2ODI5NTU2LTVlMmJkMGZlLTFiYTQtNDMxMy05MmM5LTJhN2M1MGFiY2Q0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQwNzQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Zjc5YWNjYmM1ODRlYTI4ZTk3ZGIzNzY2ZGYxZGFkNzkwODRmN2EzMGFkOGZjNTliMWUyYjRjOGFiOGFkNzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o__EX5rEo3O93CvFVq4oYygwF9x7OyyIV8MFwQ7xM_4">

这是SDK啊，可没有我需要的平台的SDK。

如果你使用 Node 的话，直接用SDK就好了啊，为什么要找接口呢？

SDK是对 ws 的加密逻辑的包装。

**Comment by WAADRI** [comment]
> conference.easemob.com
> 
> > 网页版IM确实只能获取未读消息，已读消息是获取不到的，也许可以去看看环信SDK里面有没有对应的接口？
> 
> 大佬，这个未读消息是有什么接口可以获取么

就是连上环信IM的时候给环信发一串消息代表获取一下未读消息列表，然后它每个未读消息的前后字符串都是一样的所以我在first_get_taskinfo函数里面通过正则匹配出了每个消息的ID，然后获取消息具体内容需要给环信发送具体的消息ID进行获取，就是first_get_taskinfo函数最后ws.send的东西，返回的内容按我的代码逻辑就是会进入get_message函数进行判断是否为签到消息然后进行处理

**Comment by WAADRI** [comment]
IM消息的处理我是参考了GitHub上另一位大佬用C#逆向的代码，然后将C#代码改成了python代码

**Comment by xnixianshituandui** [comment]
<img width="505" alt="image" src="https://github.com/user-attachments/assets/6e25fafc-5d6e-44f4-b6d4-46a37094cb7c">

大佬，想问一下发的这个消息内容是固定的么，是随机字符串么？我看有一个get_data_base64_decode这个

```
mess = json.loads(message[1:])[0]
mess = await get_data_base64_decode(mess)
.....
elif mess[:5] == b"\x08\x00\x40\x01\x4a":
    await first_get_taskinfo(ws, mess)
```

**Comment by Misaka-1314** [comment]
@xnixianshituandui 去群里吧，还能活跃群。这应该是属于 Discussion 而不是 Issue

**Comment by WAADRI** [comment]
![image](https://github.com/user-attachments/assets/9d076d4a-7877-4f50-80f7-0144f3c1e8df)
![image](https://github.com/user-attachments/assets/6380ca7e-e85a-4544-908d-8fc22468f981)

**Comment by Misaka-1314** [comment]
> 有老版本的文档可以看， <img alt="image" width="1116" src="https://private-user-images.githubusercontent.com/175671363/386829556-5e2bd0fe-1ba4-4313-92c9-2a7c50abcd4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NTA0MzgsIm5iZiI6MTczMTc1MDEzOCwicGF0aCI6Ii8xNzU2NzEzNjMvMzg2ODI5NTU2LTVlMmJkMGZlLTFiYTQtNDMxMy05MmM5LTJhN2M1MGFiY2Q0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQwOTQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzQ5OWZjMDNlMTRhYmIzMjQ3N2NlOTQ3ZTVjNjNlMTYzNDU1NjZlNGE5OTI4ZjBkYzk3ZDY2ZDIxZmRmNGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AORHm7qgQTj0DMj5Jb-Bl_gtQFU-4GDCYjh7XMukjf0">

我还真去试了这个接口，结果学习通用版本没有这个接口，哈哈
![image](https://github.com/user-attachments/assets/3d17374a-9049-48be-b995-429531c40520)

**Comment by xnixianshituandui** [comment]
> > 有老版本的文档可以看， <img alt="image" width="1116" src="https://private-user-images.githubusercontent.com/175671363/386829556-5e2bd0fe-1ba4-4313-92c9-2a7c50abcd4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NTA0MzgsIm5iZiI6MTczMTc1MDEzOCwicGF0aCI6Ii8xNzU2NzEzNjMvMzg2ODI5NTU2LTVlMmJkMGZlLTFiYTQtNDMxMy05MmM5LTJhN2M1MGFiY2Q0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQwOTQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzQ5OWZjMDNlMTRhYmIzMjQ3N2NlOTQ3ZTVjNjNlMTYzNDU1NjZlNGE5OTI4ZjBkYzk3ZDY2ZDIxZmRmNGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AORHm7qgQTj0DMj5Jb-Bl_gtQFU-4GDCYjh7XMukjf0">
> 
> 我还真去试了这个接口，结果学习通用版本没有这个接口，哈哈 ![image](https://private-user-images.githubusercontent.com/163623644/386835862-3d17374a-9049-48be-b995-429531c40520.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NTc4NDAsIm5iZiI6MTczMTc1NzU0MCwicGF0aCI6Ii8xNjM2MjM2NDQvMzg2ODM1ODYyLTNkMTczNzRhLTkwNDktNDhiZS1iOTk1LTQyOTUzMWM0MDUyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMTQ1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2MwYmU3MmY3OTc2MGZhNGFiMGRlMDBhZTQ5YWM4MDg1NmQyNGYyODMzMTk1NGQ3ZWRjYWQ0YWYzODE4Mjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qPh8aDSM0S2lezykOFoMIoa9Cb3Aj0xuAmON8GxrrI0)

可能学习通压根就没开通这个服务
